// Kutish ekranlarida ko'rsatiladigan qiziqarli faktlar (500+).
// Sohalar: robototexnika, dasturlash, kompyuter tarixi, AI, internet, fazo,
// o'yinlar, gadjetlar, fan-matematika, ixtirochilar va kompaniyalar.
// Javob berib bo'lgach boshqalarni kutayotganda aylanib turadi — o'quvchi zerikmaydi.
export const FACTS: string[] = [
  // ==================== ROBOTOTEXNIKA ====================
  "Birinchi sanoat roboti «Unimate» 1961-yilda General Motors zavodida ishlagan.",
  "«Robot» so'zi chexcha «robota» — «majburiy mehnat» so'zidan olingan (1920-yil).",
  "Boston Dynamics'ning Atlas roboti salto qila oladi va parkur o'ynaydi.",
  "Eng kichik robotlar inson sochidan ham ingichka — tomirlar ichida yura oladi.",
  "Yaponiyada «Henn na Hotel» mehmonxonasida sizni robot ro'yxatga oladi.",
  "Dunyodagi sanoat robotlarining yarmidan ko'pi Osiyoda ishlaydi.",
  "Da Vinci jarrohlik roboti million'lab operatsiyalarda qatnashgan.",
  "Robot chang yutgichlar (Roomba) 2002-yildan beri sotiladi.",
  "Sophia ismli gumanoid robot Saudiya Arabistoni fuqaroligini olgan (2017).",
  "ASIMO — Honda'ning mashhur gumanoid roboti — zinadan chiqa olardi.",
  "Robotlar Fukusima AESidagi halokat joyini odam o'rniga tekshirgan.",
  "Amazon omborlarida yuk tashuvchi robotlar soni yuz minglab.",
  "Dunyodagi eng tez robot qo'l Rubik kubigini 0,38 soniyada yig'adi.",
  "Robot baliqlar okeanda suv ifloslanishini kuzatish uchun suzadi.",
  "Leonardo da Vinchi 1495-yilda mexanik ritsar-robot chizmasini chizgan.",
  "RoboCup musobaqasining maqsadi — 2050-yilgacha robotlar jamoasi futbol bo'yicha jahon chempionini yengishi.",
  "Drone'lar Afrikada dori-darmonlarni uzoq qishloqlarga yetkazadi.",
  "Ba'zi fermalarda sigirlarni robotlar sog'adi — sigir o'zi navbatga keladi.",
  "Robot-sapyorlar minalarni zararsizlantirishda askarlar hayotini saqlaydi.",
  "Yaponiya — aholi jon boshiga eng ko'p robot to'g'ri keladigan davlatlardan biri.",
  "Nanorobotlar kelajakda saraton hujayralarini bitta-bitta yo'q qilishi kutilmoqda.",
  "Robot-barmen kemalarda kokteyl tayyorlab beradi — Royal Caribbean laynerlarida bor.",
  "Suv osti robotlari «Titanik» qoldiqlarini o'rganishda ishlatilgan.",
  "Spot ismli robot-it qurilish maydonchalarini avtomatik tekshiradi.",
  "Dunyoda har yili 500 mingdan ortiq yangi sanoat roboti o'rnatiladi.",
  "Robototexnikada «uch qonun»ni yozuvchi Ayzek Azimov o'ylab topgan (1942).",
  "Birinchi robot-portret rassomi Ai-Da o'z rasmlarini ko'rgazmalarda sotadi.",
  "Ekzoskelet-robotlar falaj bemorlarga qayta yurishni o'rgatadi.",
  "Robot-liftlar (paternoster) to'xtamasdan aylanib yuradi — 1884-yildan bor.",
  "Tesla zavodlarida minglab robot bitta mashinani 10 soatda yig'adi.",
  "Robotlar vulqon kraterlariga tushib, namunalar olib chiqqan.",
  "Qishloq xo'jaligi dronlari dalalarni odamdan 40 barobar tez sepadi.",
  "Robot-futbolchilar ligasida hakam ham dastur — ofsaydni aniq o'lchaydi.",
  "Xitoyda robot-ofitsiantlar ishlayotgan restoranlar mavjud.",
  "Eng katta yuruvchi robot — 15 metrli ajdaho «Tradinno», Germaniyada yasalgan.",
  "Robot qo'llar kosmik stansiyada astronavtlar o'rniga tashqi ishlarni bajaradi.",
  "O'rmon yong'inlarini kuzatuvchi dronlar issiqlik kamerasi bilan ko'radi.",
  "Robotlar arxeologiyada — piramidalar ichidagi tor yo'laklarni tekshirgan.",
  "Birinchi «mexanik o'rdak» 1739-yilda yasalgan — yem yeb, «hazm» qilardi.",
  "Robot-kutubxonachi kerakli kitobni million kitob orasidan bir necha daqiqada topadi.",

  // ==================== DASTURLASH ====================
  "Dunyodagi birinchi dasturchi — ayol: Ada Lavleys, 1843-yilda algoritm yozgan.",
  "Python tili ilon nomidan emas — «Monty Python» komediya guruhi nomidan olingan.",
  "JavaScript atigi 10 kunda yaratilgan (Brendan Eich, 1995).",
  "Birinchi kompyuter «bag»i — 1947-yilda kompyuter ichidan topilgan haqiqiy kapalak edi!",
  "«Hello, World!» an'anasi 1972-yildagi C tili darsligidan boshlangan.",
  "O'rtacha dasturchi kuniga atigi 10-50 qator «yakuniy» kod yozadi — qolgani o'ylash!",
  "Linux yadrosida 30 milliondan ortiq qator kod bor.",
  "Google'ning barcha xizmatlari ~2 milliard qator koddan iborat.",
  "Python hozir maktablarda eng ko'p o'rgatiladigan dasturlash tili.",
  "C++ tilining nomi «C ga bittani qo'shish» degan hazildan kelib chiqqan.",
  "GitHub'da 400 milliondan ortiq kod ombori (repozitoriy) bor.",
  "Dasturchilar kunini 256-kunda (13-sentabr) nishonlashadi — 2^8 sharafiga.",
  "Scratch tilida 100 milliondan ortiq bola dasturlashni o'rgangan.",
  "Java dastlab «Oak» (eman) deb nomlangan, keyin kofe navi nomi berilgan.",
  "Birinchi yuqori darajali til — Fortran (1957) hali ham fanda ishlatiladi.",
  "Minecraft dastlab atigi 6 kunda yozilgan edi.",
  "Dunyoda 700 dan ortiq dasturlash tili mavjud.",
  "Kod yozishda eng qimmat xato — Mariner 1 raketasi bitta chiziqcha tufayli portlatilgan (1962).",
  "NASA hali ham ba'zi eski loyihalarda 1970-yillar kodidan foydalanadi.",
  "Ruby tili yaratuvchisi uni «dasturchini baxtli qilish» uchun yozgan.",
  "Stack Overflow'da har kuni ~5 000 ta yangi savol beriladi.",
  "«Bug» va «debug» so'zlarini mashhur qilgan — dasturchi ayol Greys Xopper.",
  "Birinchi kompyuter virusi «Creeper» 1971-yilda yozilgan — shunchaki xabar chiqarardi.",
  "CAPTCHA ni yechayotganingizda ba'zan kitoblarni raqamlashtirishga yordam berasiz.",
  "Windows kodining katta qismi C va C++ da yozilgan.",
  "Birinchi veb-brauzer 1990-yilda yozilgan va «WorldWideWeb» deb atalgan.",
  "Dasturchilar orasida eng mashhur klaviatura tugmasi — Ctrl+C / Ctrl+V!",
  "Sun'iy yo'ldoshlar ham dasturiy yangilanish oladi — to'g'ridan-to'g'ri kosmosda.",
  "Eng qisqa dasturlash tili nomlari: C, D, F, J, K, R — bitta harf!",
  "Pac-Man o'yinining 256-darajasida xato bor — uni o'tib bo'lmaydi.",
  "Algoritm so'zi IX asr olimi Al-Xorazmiy nomidan kelib chiqqan — vatandoshimiz!",
  "Al-Xorazmiyning «Al-jabr» kitobidan «algebra» so'zi ham olingan.",
  "Birinchi onlayn banking 1980-yillarda paydo bo'lgan.",
  "Discord dastlab o'yinchilar uchun yaratilgan, endi darslarda ham ishlatiladi.",
  "Kompyuter o'yinlarining ~50% Unity yoki Unreal Engine'da yozilgan.",
  "Emojilar ham Unicode standarti — ular ham «belgi» hisoblanadi.",
  "Eng uzoq davom etgan dasturiy loyihalardan biri — 1968-yildan beri ishlayotgan aviabilet tizimi.",
  "Dasturchilarning sevimli quvvat manbai — dunyo bo'yicha yiliga milliardlab chashka kofe.",
  "Open source: Linux, Firefox, VLC — bepul va kodi ochiq, istagan odam yaxshilashi mumkin.",
  "Birinchi kompyuter o'yinlaridan biri «Spacewar!» 1962-yilda talabalar tomonidan yozilgan.",

  // ==================== KOMPYUTER TARIXI ====================
  "Birinchi elektron kompyuter ENIAC 27 tonna og'irlikda edi — butun xona hajmida.",
  "Birinchi kompyuter sichqonchasi 1964-yilda yog'ochdan yasalgan edi.",
  "Birinchi qattiq disk (1956) 5 MB sig'imda va muzlatgichdek katta edi.",
  "Bugungi smartfon Apollon oyga uchish kompyuteridan millionlab marta kuchli.",
  "Birinchi noutbuk (1981) 11 kg og'irlikda edi.",
  "«Kompyuter» so'zi dastlab hisob-kitob qiluvchi ODAMLARGA nisbatan ishlatilgan.",
  "Birinchi klaviatura yozuv mashinkasidan olingan — QWERTY 1873-yildan beri o'zgarmagan.",
  "ENIAC ni dasturlagan birinchi jamoa — olti nafar ayol matematik edi.",
  "Floppy disk belgisi «saqlash» tugmasida qolgan, lekin ko'p bolalar uni ko'rmagan!",
  "Birinchi kompyuterlar lampali edi — ming'lab lampochka kuyib turardi.",
  "Mexanik hisoblagichlar 400 yil oldin ham bo'lgan — Paskal 19 yoshida yasagan.",
  "Alan Tyuring — zamonaviy kompyuter fanining otasi — nemis shifrlarini buzgan.",
  "Birinchi Apple kompyuteri (Apple I) yog'och korpusda sotilgan (1976).",
  "IBM PC (1981) 16 KB xotira bilan chiqqan — bugungi rasm undan ming barobar katta.",
  "Kremniy vodiysi nomi mikrosxemalardagi kremniy elementidan olingan.",
  "Bir zamonaviy protsessorda 10 milliarddan ortiq tranzistor bor.",
  "Tranzistor 1947-yilda ixtiro qilingan — usiz kompyuterlar xona kattaligida qolardi.",
  "Birinchi rangli monitorlar faqat 16 rang ko'rsatardi, hozirgilari — milliondan ortiq.",
  "Mur qonuni: protsessorlar quvvati har ~2 yilda ikki baravar oshadi (1965-yildan beri).",
  "Superkompyuter «Frontier» soniyada kvintillion (10^18) amal bajaradi.",
  "SSD disklar HDD dan yuz barobar tez — ichida aylanadigan qism yo'q.",
  "USB standarti 1996-yilda chiqqan — undan oldin har qurilma o'z ulagichi bilan kelardi.",
  "Kompyuterlar ikkilik (0 va 1) tizimida ishlaydi — hammasi shu ikki raqam!",
  "Bir bayt = 8 bit; «bit» so'zi «binary digit»ning qisqartmasi.",
  "Dunyodagi barcha ma'lumotlarning 90% oxirgi bir necha yilda yaratilgan.",
  "Birinchi printer matnni sekundiga bir harf tezlikda chiqarardi.",
  "Kompyuter ekranidagi rang uch nurdan yig'iladi: qizil, yashil, ko'k (RGB).",
  "Eng kichik kompyuter — 0,3 mm, guruch donidan ham kichik (Michigan universiteti).",
  "Klaviaturada F va J tugmalarida do'ngcha bor — qo'lni qaramasdan joylash uchun.",
  "Birinchi smartfon 1994-yilda chiqqan — IBM Simon, narxi 899 dollar edi.",
  "Kompyuter xotirasi «RAM» o'chirilganda tozalanadi, disk esa saqlab qoladi.",
  "O'yin konsollari ham kompyuter — PlayStation 5 protsessori noutbuknikidan kuchli.",
  "Birinchi veb-kamera Kembrijda kofe idishini kuzatish uchun o'rnatilgan (1991).",
  "Eng ko'p sotilgan kompyuter — Commodore 64 (1982), ~17 million dona.",
  "Kompyuterlar dastlab perfokartalar — teshikli kartochkalar bilan dasturlangan.",
  "Bill Geyts maktabda tunlari yashirincha kompyuter xonasida dasturlashni o'rgangan.",
  "Zamonaviy avtomobilda 100 milliondan ortiq qator kod ishlaydi — samolyotdan ko'p!",
  "Dunyodagi eng qimmat kompyuter xatosi — Ariane 5 raketasi (1996): 370 mln dollar.",
  "Birinchi «portativ» telefon 1973-yilda 1,1 kg edi va 30 daqiqa gaplashardi.",
  "Kalkulyator soati Casio 1980-yillarda eng «aqlli» gadjet hisoblangan.",

  // ==================== SUN'IY INTELLEKT ====================
  "AI shaxmat bo'yicha jahon chempionini birinchi marta 1997-yilda yenggan (Deep Blue).",
  "ChatGPT kabi AI modellari trillionlab so'zni «o'qib» o'rganadi.",
  "AlphaGo 2016-yilda Go o'yinida jahon chempionini yengdi — bu imkonsiz deyilardi.",
  "«Sun'iy intellekt» atamasi 1956-yilda Dartmut konferensiyasida paydo bo'lgan.",
  "AI rentgen suratlaridan ba'zi kasalliklarni shifokordan aniqroq topa oladi.",
  "Tyuring testi: mashina odam bilan yozishmada o'zini odam deb ishontira olsa — o'tdi.",
  "AI musiqa yozadi, rasm chizadi va hatto she'r ham to'qiydi.",
  "Ovozli yordamchilar (Siri, Alisa) — nutqni matnga aylantiruvchi AI.",
  "AI tarjimonlari 100 dan ortiq tilni bir-biriga o'giradi.",
  "Neyron tarmoqlar inson miyasidagi neyronlardan ilhomlangan.",
  "Birinchi chatbot ELIZA 1966-yilda yozilgan — psixologni taqlid qilardi.",
  "AI o'zi o'ynab o'rganadi: AlphaZero shaxmatni 4 soatda «noldan» o'zlashtirgan.",
  "Yuzni tanish AI millionlab yuz orasidan bir soniyada topadi.",
  "Spam-filtrlar ham AI — ular har kuni milliardlab keraksiz xatni to'sadi.",
  "AI ob-havoni tobora aniqroq bashorat qilmoqda.",
  "Haydovchisiz taksilar ba'zi shaharlarda allaqachon yo'lovchi tashiydi.",
  "AI yangi dori molekulalarini ham izlaydi — yillik ishni oylarga qisqartiradi.",
  "GPT'dagi «T» — Transformer: 2017-yilda ixtiro qilingan arxitektura.",
  "AI eski, buzilgan fotosuratlarni tiklab, rangli qila oladi.",
  "Deepfake — AI yasagan soxta video; ko'rganingizga har doim ishonmang!",
  "AI protein tuzilishini bashorat qilib (AlphaFold) biologiyada inqilob qildi.",
  "Tavsiya tizimlari (YouTube, Netflix) sizga nimani ko'rsatishni AI hal qiladi.",
  "AI modellarini o'qitish uchun minglab GPU haftalab ishlaydi.",
  "Kichik AI modellari endi telefonning o'zida ham ishlaydi — internetsiz.",
  "AI qadimiy yozuvlarni o'qishga yordam beradi — kuygan o'ramalarni ham «ochadi».",
  "Birinchi AI qishi: 1970-yillarda umidlar oqlanmay, moliyalash to'xtagan edi.",
  "AI satellit suratlaridan o'rmon kesilishini avtomatik aniqlaydi.",
  "Ba'zi AI'lar o'yinlarda «aldashni» o'zi kashf qilgan — qoidadagi teshikni topib.",
  "AI imlo xatolaringizni to'g'irlaydi — klaviaturadagi avtotuzatish ham shu.",
  "AI yordamida gapira olmaydigan insonlar fikrini matnga aylantirish o'rganilmoqda.",
  "Mashinali o'qitishda ma'lumot — eng qimmat boylik: «Data — yangi neft».",

  // ==================== INTERNET ====================
  "Internetdagi birinchi sayt hali ham ishlaydi: info.cern.ch (1991-yil).",
  "Dunyoda har kuni 300 milliarddan ortiq elektron xat yuboriladi.",
  "Google qidiruvi soniyada ~100 000 so'rovga javob beradi.",
  "Birinchi elektron xat 1971-yilda yuborilgan — muallifi o'zi ham matnini eslamaydi.",
  "«WWW» va «Internet» bir narsa emas: internet — tarmoq, veb — undagi xizmat.",
  "Wi-Fi texnologiyasi dastlab qora tuynuklarni izlash tadqiqotidan chiqqan.",
  "Okean tubidan o'tgan kabellari internetning ~99% trafigini tashiydi.",
  "Birinchi YouTube videosi — «Men at the zoo» (2005), 19 soniya.",
  "QR-kod 1994-yilda Yaponiyada avtomobil zavodida ixtiro qilingan.",
  "Bir daqiqada YouTube'ga 500 soatdan ortiq video yuklanadi.",
  "Emoji 1999-yilda Yaponiyada paydo bo'lgan — dastlab 176 ta edi.",
  "@ belgisi elektron pochtada 1971-yildan ishlatiladi.",
  "Birinchi banner-reklama 1994-yilda chiqqan — bosish darajasi 44% edi!",
  "Google nomi «googol» (10^100 soni) so'zining xato yozilishidan kelib chiqqan.",
  "Internet «paketlar» bilan ishlaydi — xabaringiz bo'laklarga bo'linib yetadi.",
  "DNS — internetning «telefon kitobi»: nomlarni raqamli manzillarga o'giradi.",
  "Dunyo aholisining 60% dan ortig'i internetdan foydalanadi.",
  "Birinchi smaylikni :-) 1982-yilda professor Skott Falman taklif qilgan.",
  "Wikipedia'ni istalgan odam tahrirlashi mumkin — millionlab ko'ngilli yozadi.",
  "Har kuni Google'dagi qidiruvlarning ~15% ilgari hech qachon so'ralmagan!",
  "Bluetooth nomi X asr Daniya qiroli Harald «Ko'k tish» sharafiga qo'yilgan.",
  "Internetni «o'chirib qo'yadigan» yagona tugma mavjud emas — u markazsiz.",
  "HTTP'dagi «404» xatosi — sahifa topilmadi degani; raqam xona nomeridan degan afsona bor.",
  "Streaming videolar internet trafigining yarmidan ko'pini tashkil qiladi.",
  "Birinchi ijtimoiy tarmoqlardan biri — SixDegrees (1997).",
  "Elektron pochtadagi «spam» nomi Monty Python sketchidagi konservadan olingan.",
  "Optik tola ichida ma'lumot yorug'lik tezligiga yaqin uchadi.",
  "Internetdagi parollarning eng mashhuri hali ham «123456» — bunday qilmang!",
  "HTTPS'dagi «S» — Secure: ma'lumotlaringiz shifrlangan holda uchadi.",
  "Birinchi onlayn xarid 1994-yilda qilingan — Sting'ning musiqa diski edi.",
  "Yer sharini o'rab olgan sun'iy yo'ldosh internetlari (Starlink) samolyotda ham ishlaydi.",
  "Bir Google qidiruvi javobi sizga yetguncha minglab kilometr yo'l bosadi.",
  "Captcha so'zi — «Completely Automated Public Turing test...» qisqartmasi.",
  "Dunyodagi eng katta onlayn ensiklopediya — Wikipedia, 300 dan ortiq tilda.",
  "Ba'zi davlatlarda internet sham baholi — Yaponiyada dunyodagi eng tez uy interneti.",

  // ==================== FAZO / KOSMOS ====================
  "Kosmosdagi astronavtlar bo'yi 5 sm gacha o'sadi — vaznsizlik tufayli.",
  "Marsdagi Perseverance roveri kuniga o'rtacha atigi 100 metr yuradi — lekin juda aniq.",
  "Yer atrofida 8000 dan ortiq sun'iy yo'ldosh aylanmoqda.",
  "Yorug'lik Quyoshdan Yerga ~8 daqiqa 20 soniyada yetib keladi.",
  "Xalqaro kosmik stansiya soatiga ~28 000 km tezlikda uchadi.",
  "XKSda astronavtlar kuniga 16 marta quyosh chiqishini ko'radi.",
  "Venera o'z o'qi atrofida teskari aylanadi — u yerda Quyosh g'arbdan chiqadi.",
  "Neytron yulduzning bir qoshiq moddasi milliardlab tonna keladi.",
  "Oyda shamol yo'q — astronavtlar izi millionlab yil saqlanadi.",
  "Yupiterning Buyuk qizil dog'i — Yerdan katta bo'ron, 300 yildan beri esadi.",
  "Kosmos butunlay jim — tovush tarqalishi uchun havo kerak.",
  "Saturn zichligi suvdan past — ulkan hovuz bo'lsa, suzib yurardi!",
  "Bir yil ichida Voyager-1 zondi Yerdan 24 milliard km dan uzoqlashdi — eng olis inson buyumi.",
  "Quyosh tizimidagi eng baland tog' Marsda: Olimp — 21 km, Everestdan 2,5 barobar baland.",
  "Astronavt skafandri narxi millionlab dollar turadi.",
  "Kosmosda yig'lasangiz — ko'z yoshi oqmaydi, shar bo'lib yig'iladi.",
  "Oy har yili Yerdan ~3,8 sm uzoqlashmoqda.",
  "Merkuriyda bir kun (aylanish) ikki yildan uzun davom etadi.",
  "Birinchi kosmonavt Yuriy Gagarin 108 daqiqada Yerni aylangan (1961).",
  "Birinchi sun'iy yo'ldosh «Sputnik-1» basketbol to'pidek edi (1957).",
  "Hubble teleskopi 13 milliard yil avvalgi galaktikalar nurini ko'radi.",
  "James Webb teleskopi oltin qoplamali oynalari bilan infraqizilda ko'radi.",
  "Mars qizil — tuprog'ida zang (temir oksidi) ko'pligidan.",
  "Somon yo'li galaktikamizda 100 milliarddan ortiq yulduz bor.",
  "Qora tuynukdan hatto yorug'lik ham qochib chiqa olmaydi.",
  "Xalqaro kosmik stansiyada suv qayta ishlanadi — hatto ter va nafasdan ham.",
  "Astronavtlar kosmosda kuniga 2 soat sport bilan shug'ullanadi — mushak so'nmasligi uchun.",
  "Kosmik stansiyagacha «atigi» 400 km — Toshkentdan Samarqandgacha bo'lgan masofa.",
  "Oyga 12 kishi qadam bosgan — hammasi 1969–1972-yillarda.",
  "Kometalar «iflos qor parchalari» — muz va changdan iborat.",
  "Quyosh har soniyada millionlab tonna massasini energiyaga aylantiradi.",
  "Uranning aylanish o'qi «yotiq» — u yonboshlab aylanadi.",
  "Yerning ozon qatlami bizni Quyosh ultrabinafshasidan qalqon kabi saqlaydi.",
  "Mars vertolyoti Ingenuity boshqa sayyorada uchgan birinchi apparat (2021).",
  "Kosmik chiqindilar ham muammo — orbitada millionlab mayda parcha uchib yuribdi.",
  "O'zbekistonlik birinchi kosmonavt — Vladimir Djanibekov, 5 marta kosmosda bo'lgan.",
  "Quyosh Yerdan 109 barobar keng — ichiga million dona Yer sig'adi.",
  "Yulduzlar «miltillashi» — yorug'likning atmosferada sinishi, kosmosda ular tinch yonadi.",
  "Pluton 2006-yilda «sayyoralik»dan chiqarilib, mitti sayyora deb qayta tasniflangan.",
  "Andromeda galaktikasi biz tomon ~110 km/s tezlikda kelmoqda — 4 mlrd yildan keyin qo'shilamiz.",

  // ==================== O'YINLAR ====================
  "Birinchi videoo'yin 1958-yilda osteoskopda yaratilgan — «Tennis for Two».",
  "Tetris o'yini 1984-yilda Moskvada bitta dasturchi tomonidan yaratilgan.",
  "Mario dastlab «Jumpman» deb atalgan va u duradgor edi.",
  "Minecraft — tarixdagi eng ko'p sotilgan o'yin: 300 milliondan ortiq nusxa.",
  "Pac-Man'ning shakli pitsadan bir bo'lak olib qo'yilganda paydo bo'lgan g'oya.",
  "Birinchi o'yin konsoli Magnavox Odyssey (1972) televizorga plyonka yopishtirardi.",
  "Kiberspot musobaqalari stadionlarni to'ldiradi — sovrinlar millionlab dollar.",
  "Sonic tipratikan tezligi uchun tanlangan — raqib Mario'dan «tezroq» bo'lishi kerak edi.",
  "Game Boy (1989) shu qadar mustahkam ediki, urushda kuyganlari ham ishlagan.",
  "Lego yiliga 700 milliondan ortiq g'ildirakcha ishlab chiqaradi — dunyodagi eng katta «shina zavodi».",
  "Roblox'dagi o'yinlarni asosan o'yinchilarning o'zi yaratadi.",
  "«Easter egg» (yashirin sovg'a) an'anasi 1979-yilgi Adventure o'yinidan boshlangan.",
  "Wii pulti tufayli millionlab televizor ekrani singan — kaftdan sirg'alib uchgan!",
  "Speedrun — o'yinni rekord tezlikda o'tish sporti; soniya uchun kurash boradi.",
  "Pokemon Go odamlarni ko'chaga chiqardi — bir oyda 100 million yuklab olish.",
  "O'yin dizaynerlari «qiyin, lekin adolatli» muvozanatini yillab sozlaydi.",
  "Birinchi o'yin musiqasi bitta melodiya edi — hozir orkestrlar yozadi.",
  "The Legend of Zelda'da saqlash funksiyasi birinchi bo'lib batareyali kartrijda chiqqan.",
  "Fortnite'ning bir jonli konsertini o'yin ichida millionlab kishi tomosha qilgan.",
  "Shaxmat dvijoklari (Stockfish) istalgan grossmeysterni yengadi — telefoningizda ham.",
  "Kompyuter o'yinlarining ~50% Unity yoki Unreal Engine'da yaratilgan.",
  "Doom (1993) shu qadar mashhur ediki, «Doom ishlaydimi?» texnika testiga aylangan.",
  "O'yinlarda «lag» — signalning serverga borib kelish kechikishi (ping).",
  "Sims'dagi «Simlish» tili — maxsus o'ylab topilgan mavjud bo'lmagan til.",
  "Retro o'yin kartrijlarini puflash aslida yordam bermagan — shunchaki odat edi!",

  // ==================== GADJETLAR VA TEXNOLOGIYA ====================
  "Birinchi iPhone 2007-yilda chiqqan — ilovalar do'koni hali yo'q edi.",
  "Smartfoningizdagi kamera 90-yillardagi professional kameralardan kuchli.",
  "Dunyoda odamlardan ko'ra ko'proq mobil qurilma bor.",
  "Batareya foizi yolg'on gapirishi mumkin — u taxminiy hisob.",
  "Simsiz quvvatlash aslida 19-asrda Tesla g'oyalaridan boshlangan.",
  "Birinchi SMS 1992-yilda yuborilgan: «Merry Christmas».",
  "Telefonlarning vibratsiyasi — ichidagi kichkina aylanuvchi og'irlik.",
  "GPS harbiylar uchun yaratilgan, keyin hammaga ochilgan.",
  "GPS soatlari nisbiylik nazariyasiga tuzatish kiritadi — aks holda kuniga ~10 km adashardik!",
  "Sensorli ekran barmoq elektr o'tkazuvchanligini sezadi — qo'lqopda ishlamasligi shundan.",
  "Dunyodagi birinchi fotosurat 1826-yilda olingan — 8 soat ekspozitsiya kerak bo'lgan.",
  "Naushnikdagi «shovqin bekor qilish» — qarshi tovush to'lqini chiqarish.",
  "Bir soatlik video yozish uchun 90-yillarda butun videokasseta kerak edi.",
  "Smart soatlar yurak urishini yorug'lik bilan o'lchaydi — teridagi qon oqimini «ko'radi».",
  "Ekran «piksel»lari — juda mayda qizil-yashil-ko'k chiroqchalar.",
  "Birinchi planshet g'oyasi 1968-yilda chizilgan — «Dynabook», bolalar uchun!",
  "eSIM — jismoniy SIM-kartasiz telefon raqami; kartani qirqish davri tugayapti.",
  "Kompas ilovasi telefondagi magnitometr sensori bilan ishlaydi.",
  "Suv o'tkazmaydigan telefonlar IP68 — 1,5 metr suvda yarim soat chidaydi.",
  "Zaryadlovchi simlarning ichida bir nechta alohida sim bor — quvvat va ma'lumot alohida.",
  "Face ID yuzingizga 30 000 ko'rinmas nuqta sochib, 3D xarita quradi.",
  "Birinchi raqamli kamera (1975) 3,6 kg edi va oq-qora surat olardi.",
  "Powerbank'lar samolyotda faqat qo'l yukida ruxsat etiladi — batareya xavfsizligi.",
  "Dunyoda har soniyada yuzlab yangi telefon sotiladi.",
  "5G — 4G dan o'nlab barobar tez; jarrohlar masofadan operatsiya qilishiga imkon beradi.",

  // ==================== FAN VA MATEMATIKA ====================
  "Inson miyasi ~86 milliard neyronga ega — eng kuchli «kompyuter» hali ham bizda!",
  "Nol raqamini matematikaga hindlar kiritgan, arab olimlari dunyoga tarqatgan.",
  "Pi soni cheksiz — kompyuterlar uni 100 trilliondan ortiq raqamgacha hisoblagan.",
  "Chaqmoq harorati Quyosh sirtidan ~5 barobar issiq.",
  "Asalarilar oltiburchak katak quradi — bu eng tejamkor geometrik shakl.",
  "Bir varaq qog'ozni 42 marta buklasangan, qalinligi Oygacha yetardi (nazariy).",
  "Fibonachchi sonlari gulbarglar va chig'anoqlarda uchraydi: 1,1,2,3,5,8...",
  "Yorug'lik tezligi — 299 792 458 m/s; undan tez hech narsa uchmaydi.",
  "DNK molekulasini cho'zsangiz, bitta hujayranikida ~2 metr chiqadi.",
  "Suv yuqoriga qarab ham «yuradi» — o'simliklar ildizidan barggacha kapillyarlik bilan.",
  "Atom deyarli bo'shliq: yadro stadion o'rtasidagi nohotdek, elektronlar chetlarda.",
  "Bir chaqnashda chaqmoq millionlab lampochkani yoqadigan energiya beradi.",
  "Tovush suvda havodagidan ~4,3 barobar tez tarqaladi.",
  "Yerning ichki yadrosi Quyosh sirti kabi issiq — ~5500°C.",
  "Eng qattiq tabiiy modda — olmos, lekin bolg'a bilan ursangiz sinadi!",
  "Bakteriyalar Yerdagi eng ko'p tirik organizmlar — tanamizda ham trillionlab.",
  "Nurning sinishi tufayli suvga botgan qoshiq singandek ko'rinadi.",
  "Kosmosdan qaraganda Buyuk Xitoy devori oddiy ko'z bilan deyarli ko'rinmaydi.",
  "Bir kunda yurak ~100 000 marta uradi.",
  "Sof oltin shu qadar yumshoqki, tish bilan iz qoldirsa bo'ladi.",
  "Magnit kompas ko'rsatadigan «shimol» geografik shimoldan biroz farq qiladi.",
  "Eng kichik o'lchov birliklaridan biri — nanometr: soch tolasi ~80 000 nm.",
  "Aynan matematika tufayli GPS, shifrlash va grafika mavjud.",
  "Ehtimollik: 23 kishilik sinfda ikkitasining tug'ilgan kuni bir xil chiqish ehtimoli 50%!",
  "Nol faktorial (0!) = 1 — matematiklar shunday kelishgan, formulalar ishlashi uchun.",
  "Yer aylanishi sekinlashmoqda — million yil oldin kun ~23 soat edi.",
  "Bug'doy donini shaxmat taxtasiga 2 barobarlab qo'yib chiqsangiz — dunyo hosilidan ko'p chiqadi.",
  "Suvning eng zich holati +4°C — shu tufayli muz suzadi va baliqlar qishda omon qoladi.",
  "Binar tizimda 10 — bu ikki; «Dunyoda 10 xil odam bor: binarni tushunadigan va yo'q» degan hazil bor.",
  "Eyfel minorasi yozda issiqdan ~15 sm ga «o'sadi» — metall kengayadi.",

  // ==================== IXTIROCHILAR VA KOMPANIYALAR ====================
  "Arduino platasi Italiyadagi bar nomidan olingan — ixtirochilar o'sha yerda yig'ilishardi.",
  "Raspberry Pi — 35 dollarlik kompyuter — bolalarga dasturlash o'rgatish uchun yaratilgan.",
  "Apple, Google va Amazon garajda boshlangan kompaniyalar.",
  "Nokia dastlab qog'oz fabrikasi bo'lgan (1865), keyin rezina etik ham chiqargan!",
  "Samsung 1938-yilda quritilgan baliq va noodle sotishdan boshlagan.",
  "YouTube dastlab tanishuv sayti sifatida o'ylangan edi.",
  "Instagram dastlab «Burbn» nomli check-in ilovasi edi.",
  "Tim Berners-Li WWW ni ixtiro qilib, uni patentlamadi — hammaga bepul berdi.",
  "Nintendo 1889-yilda o'yin kartalari ishlab chiqarishdan boshlagan.",
  "Dyson o'z changyutgichini yaratguncha 5127 ta prototip yasagan.",
  "Bluetooth belgisi — qirol Harald ismining runiy harflari birikmasi.",
  "Twitter'dagi birinchi tvit: «just setting up my twttr» (2006).",
  "Amazon'da birinchi sotilgan mahsulot — kitob edi (1995).",
  "Tesla kompaniyasi olim Nikola Tesla sharafiga nomlangan.",
  "Volta, Amper, Om, Vatt — bularning bari olimlar nomi.",
  "Grace Hopper birinchi kompilyatorni yaratgan — «kod odamga tushunarli bo'lsin» degan.",
  "Xerox laboratoriyasi sichqoncha va grafik interfeysni birinchi ko'rsatgan — Apple ilhomlangan.",
  "LEGO nomi daniyacha «leg godt» — «yaxshi o'yna» degani.",
  "WhatsApp'ni ikki kishi boshlagan, keyin 19 mlrd dollarga sotilgan.",
  "Netflix dastlab DVD'larni pochta orqali ijaraga berardi.",
  "Al-Beruniy 1000 yil oldin Yer radiusini hayratlanarli aniqlikda o'lchagan — vatandoshimiz!",
  "Ibn Sino «Tib qonunlari» kitobi Yevropada 600 yil darslik bo'lgan.",
  "Ulug'bek rasadxonasi XV asrda yulduzlarni shunday aniq o'lchaganki, hozirgi hisob-kitoblarga yaqin.",
  "Mirzo Ulug'bek jadvalidagi 1018 yulduz koordinatalari asrlar davomida ishlatilgan.",
  "Kompyuter sichqonchasi ixtirochisi Duglas Engelbart unga patentdan deyarli pul olmagan.",
  "Braille yozuvini 15 yoshli Lui Brayl o'ylab topgan.",
  "Velcro (chirt-yopishqoq) it juniga yopishgan o'simlik urug'idan ilhomlangan.",
  "Mikroto'lqinli pech tasodifan ixtiro qilingan — radar yonida shokolad erib ketgan.",
  "Plastilin dastlab devor tozalagich sifatida sotilgan.",
  "Coca-Cola logotipi 130 yildan beri deyarli o'zgarmagan.",
  "Adidas va Puma — bir-biri bilan arazlashgan aka-ukalar kompaniyalari.",
  "Toshkent metrosi Markaziy Osiyodagi birinchi metro (1977).",
  "SpaceX raketalari qaytib qo'nadi va qayta uchadi — ilgari raketalar bir martalik edi.",
  "Wright aka-ukalarning birinchi parvozi 12 soniya davom etgan (1903).",
  "Bugungi yo'lovchi samolyotining qanotida million detalga yaqin qism bor.",

  // ==================== QO'SHIMCHA TEXNO-FAKTLAR ====================
  "Klaviaturada eng ko'p bosiladigan tugma — bo'shliq (space).",
  "Monitor 60 Hz bo'lsa — sekundiga 60 marta rasm yangilanadi; o'yin monitorlari 240+ Hz.",
  "Fayl .zip qilinganda takrorlanuvchi qismlar qisqa yozuv bilan almashtiriladi.",
  "MP3 formati inson qulog'i sezmaydigan tovushlarni olib tashlab siqadi.",
  "PNG rasmlari sifat yo'qotmaydi, JPEG esa siqishda ozgina «yumshatadi».",
  "Bir HD film — taxminan 4-5 GB; 90-yillardagi qattiq disklar 100 tasiga yetmasdi.",
  "Kompyuterda «yadro» (core) qancha ko'p bo'lsa — shuncha parallel ish bajaradi.",
  "Fanlarning ko'pida simulyatsiya ishlatiladi: ob-havo, avtohalokat testlari, epidemiya.",
  "Kriptografiya qadimda ham bo'lgan — Yuliy Sezar harflarni 3 ga surib shifrlagan.",
  "Enigma shifrini buzish Ikkinchi jahon urushini qisqartirgan deb hisoblanadi.",
  "Kvant kompyuterlari 0 va 1 ni bir vaqtda saqlay oladi (superpozitsiya).",
  "Ekran skrinshoti ham fayl — u RAMdagi tasvirning nusxasi.",
  "Ba'zi ma'lumot markazlari sovutish uchun okean ostiga joylashtirilgan.",
  "Google ma'lumot markazlari yiliga kichik shahar sarflaydigan tok ishlatadi.",
  "Fayl o'chirilganda u darrov yo'qolmaydi — faqat «bo'sh joy» deb belgilanadi.",
  "Parolni «tuzlash» (salt) — bazada bir xil parollar har xil ko'rinishi uchun.",
  "Ikki faktorli autentifikatsiya hisobingizni o'g'irlanishdan ~99% himoya qiladi.",
  "Klaviatura yotqizilishi QWERTY yozuv mashinkasi richaglarini ilashtirmaslik uchun tanlangan.",
  "Dunyoda eng ko'p ishlatiladigan ofis dasturi — elektron jadval (Excel kabi).",
  "Excel'da 1900-yil xato «kabisa» hisoblanadi — Lotus 1-2-3 ga moslik uchun ataylab qoldirilgan.",
  "Kompyuter soati maxsus kristall tebranishi bilan yuradi — sekundiga millionlab marta.",
  "Ba'zi saytlar «dark mode»da kam quvvat sarflaydi — OLED ekranlarda qora piksel o'chiq turadi.",
  "Robot ovozini odamga o'xshatish — TTS (text-to-speech) texnologiyasi.",
  "Sun'iy yo'ldosh fotosuratlari yordamida ekin hosili oldindan baholanadi.",
  "3D printer uy ham «bosib chiqaradi» — beton qatlamlab quyiladi.",
  "3D printerlar kosmosda ham ishlagan — XKSda ehtiyot qism chop etilgan.",
  "Smart uy: chiroq, eshik, isitish — hammasi telefondan boshqariladi.",
  "Elektromobil dvigatelida benzin motoridagidan o'n barobar kam harakatlanuvchi qism bor.",
  "Kod muharrirlaridagi rang-barang matn — «syntax highlighting», xatoni tez ko'rish uchun.",
  "Dasturlar versiyasi 1.0, 1.1, 2.0... — katta raqam katta yangilanish degani.",
  "Wi-Fi parolsiz ochiq tarmoqlarda ma'lumotni «tinglash» oson — ehtiyot bo'ling.",
  "Bulutli saqlash — aslida boshqa birovning kuchli kompyuterlari.",
  "Serverlar 24/7 ishlaydi — sayt «uxlamaydi».",
  "Ping vaqti millisekundlarda o'lchanadi — 20 ms juda yaxshi, 200 ms sezilarli kechikish.",
  "Ekranda oq rang — qizil, yashil va ko'kning to'liq yonishi.",
  "Antivirus dasturlari fayllarni ma'lum «imzo»lar bilan solishtiradi.",
  "Ochiq kodli dasturlarni dunyo bo'ylab minglab ko'ngilli birga yozadi.",
  "Dasturlashda «refactoring» — kodni ishini o'zgartirmasdan chiroyli qilish.",
  "Kompyuter o'yinidagi fizika ham matematika — har sakrash formula bilan hisoblanadi.",
  "Grafik kartalar (GPU) endi faqat o'yin uchun emas — AI o'qitishning yuragi.",
  "Bitta zamonaviy GPU'da o'n minglab mayda hisoblash yadrolari bor.",
  "Klaviatura + sichqonchadan tezroq ishlash uchun dasturchilar «hotkey»larni yodlaydi.",
  "Dunyodagi ko'p bankomatlar hali ham juda eski tizimlarda ishlaydi.",
  "Shtrix-kod birinchi marta saqichga urilgan (1974).",
  "PDF format 1993-yilda chiqqan — «har qanday qurilmada bir xil ko'rinsin» g'oyasi.",
  "Elektron kitob siyohi (e-ink) quvvatni faqat sahifa almashganda sarflaydi.",
  "Simsiz naushniklar orasida signal radioto'lqin — Bluetooth 2,4 GHz chastotada.",
  "Dunyodagi eng katta harf-raqam jumboqlaridan biri — parol topish emas, uni ESLAB QOLISH!",
  "Kompyuter «muzlab qolsa» — ko'pincha bitta dastur boshqalarga navbat bermayapti.",
  "Ctrl+Z (bekor qilish) — insoniyatning eng sevimli ixtirolaridan biri!",

  // ==================== TABIAT VA TEXNOLOGIYA ====================
  "Delfinlar sonar bilan «ko'radi» — sun'iy sonarlar ham shundan ilhomlangan.",
  "Ninachi ko'zi ~30 000 linzadan iborat — kamera dizaynerlari o'rganadi.",
  "O'rgimchak ipi po'latdan (og'irligiga nisbatan) mustahkam — sun'iysi ustida ishlanmoqda.",
  "Qushlar V shaklda uchishi 70% energiya tejaydi — dronlar ham shunday sinovdan o'tgan.",
  "Lotus bargi o'z-o'zini tozalaydi — shundan «o'zi tozalanadigan» oynalar chiqqan.",
  "Chumolilar yo'l topishda feromon izi qoldiradi — algoritmlar ham shu usulni ko'chirgan.",
  "Ko'rshapalak exolokatsiyasi — parkovka sensorlarining «bobosi».",
  "Akula terisi suvda qarshilikni kamaytiradi — suzish kostyumlariga ko'chirilgan.",
  "Asalari raqsi — koordinata tili: qayerda gul borligini raqs bilan aytadi.",
  "Tabiat 3,8 milliard yillik «laboratoriya» — biomimikriya fani undan ko'chiradi.",
  "Yaproqning fotosintezi — quyosh panelidan hali ham samaraliroq jarayonlardan biri.",
  "Termit uyalari tabiiy ventilyatsiyaga ega — binolar shundan andoza oladi.",
  "Mushuk qorong'uda ko'rishi — ko'z tubidagi «ko'zgu» qatlam tufayli; yo'l belgilarida ham shu aks ettirgichlar.",
  "Ilonlar issiqlikni «ko'radi» — issiqlik kameralari xuddi shu vazifani bajaradi.",
  "Baliqlar yon chizig'i suv tebranishini sezadi — suv osti robotlariga sensor bo'lgan.",

  // ==================== ENERGIYA VA KELAJAK ====================
  "Quyosh panellari 1 soatda Yerga tushadigan energiya — insoniyatning 1 yillik ehtiyojidan ko'p.",
  "Shamol turbinasining bitta qanoti 80 metrgacha — futbol maydonidan uzun.",
  "Elektromobillar tormozlaganda batareyani quvvatlaydi (rekuperatsiya).",
  "Yashil vodorod — suvdan tok bilan olinadigan toza yoqilg'i.",
  "Dunyodagi eng katta batareyalar butun shaharni bir necha soat quvvatlaydi.",
  "Geotermal energiya — Yer ichki issiqligidan tok olish; Islandiya deyarli to'liq shunda.",
  "Termoyadro (fuziya) — Quyoshdagi jarayonni Yerda takrorlash; «sun'iy quyosh» reaktorlari qurilmoqda.",
  "Suv to'lqinlaridan ham tok olinadi — to'lqin elektrostansiyalari.",
  "LED lampalar odatdagi lampadan ~10 barobar kam tok yeydi.",
  "Sahroga qurilgan quyosh fermalari kosmosdan ko'rinadi.",
  "Elektr samolyotlar sinovda — qisqa masofalar uchun allaqachon uchmoqda.",
  "Aqlli tarmoqlar (smart grid) tokni kerakli joyga avtomatik taqsimlaydi.",
  "Uyingizdagi eski telefon zaryadlagichi ham tokda qolsa ozgina quvvat yeydi.",
  "Atom elektrostansiyasi bir tabletka urandan bir tonna ko'mir energiyasini beradi.",
  "Kelajak shaharlarida binolar o'z tokini o'zi ishlab chiqarishi rejalanmoqda.",

  // ==================== RAQAMLAR VA REKORDLAR ====================
  "Bir soniyada dunyoda ~30 000 GB internet-trafik oqadi.",
  "Eng tez superkompyuter bir soniyada har bir yer yuzi odamiga milliardlab amal bajarib beradi.",
  "Google'ning birinchi serveri LEGO g'ishtlaridan yig'ilgan korpusda edi.",
  "Dunyodagi eng uzun kod bazalaridan biri — Windows: ~50 million qator.",
  "Minutiga dunyoda ~6 million Google qidiruvi amalga oshadi.",
  "Eng qimmat domen nomlaridan biri — cars.com, ~872 million dollarga baholangan.",
  "Bir kunlik YouTube tomoshasi — milliard soatdan ortiq.",
  "Eng ko'p yuklab olingan ilovalar — messenjerlar va qisqa video ilovalari.",
  "Dunyoda soniyasiga ~9 000 ta tvit yoziladi.",
  "Eng katta ma'lumot markazlari yuz futbol maydonicha keladi.",
  "Bitta zamonaviy chip ishlab chiqaruvchi zavod ~20 milliard dollar turadi.",
  "Chip ustidagi yo'lakchalar kengligi — bir necha nanometr: virusdan ham kichik!",
  "Eng ko'p tilga tarjima qilingan sayt — Wikipedia emas, Iegova guvohlari sayti (1000+ til); Wikipedia ~330 tilda.",
  "Kunlik elektron xatlarning ~45% — spam.",
  "O'rtacha odam telefonini kuniga ~100 marta qo'liga oladi.",
  "Eng uzoq ishlagan sun'iy yo'ldoshlardan biri 60 yildan beri orbitada.",
  "Dunyo bo'ylab bir yilda ~1,5 milliard smartfon sotiladi.",
  "Bir bitkoin tranzaksiyasi katta energiya sarflaydi — shuning uchun «yashil» alternativlar izlanmoqda.",
  "Eng katta raqamli rasm — milliardlab piksel: butun osmon xaritalari.",
  "Insoniyatning barcha so'zlashuvlari bir kunlik internet-trafikdan kam joy egallaydi.",

  // ==================== XAVFSIZLIK VA ODOB ====================
  "Kuchli parol — uzun parol: 4 tasodifiy so'z 8 belgili murakkabdan yaxshi.",
  "Hech bir bank sizdan SMS-kodni so'ramaydi — so'ragan firibgar!",
  "Telefondagi ilovalarga keraksiz ruxsat bermang — fonar ilovasiga kontaktlar shart emas.",
  "Ikki xil saytda bitta parol — bittasi buzilsa, ikkalasi ham qo'ldan ketadi.",
  "Fishing — «baliq ovi»: soxta sayt sizdan parol «tutib» oladi. Manzilni tekshiring!",
  "Ekran vaqti belgilang — ko'z ham, miya ham dam olishi kerak.",
  "Internetdagi ma'lumot abadiy qoladi deb hisoblang — joylashdan oldin o'ylang.",
  "HTTPS qulfchasi bor sayt — ma'lumot shifrlangan, lekin sayt «halol» degani emas.",
  "Dasturlarni faqat rasmiy do'kondan yuklab oling.",
  "Noma'lum USB fleshkani kompyuterga tiqmang — virus shu yo'l bilan ham yuqadi.",
  "Yangilanishlarni o'tkazib yubormang — ko'pi xavfsizlik tuzatishlari.",
  "Backup — eng yaxshi do'st: muhim fayllardan nusxa saqlang.",
  "Ochiq Wi-Fi'da bank ilovasiga kirmaslik yaxshiroq.",
  "Kibersport ham sport — lekin ko'z gimnastikasi va tanaffus shart!",
  "Internetda notanish odamga uy manzilingizni hech qachon bermang.",

  // ==================== YANA TEXNO-FAKTLAR ====================
  "Birinchi kompyuter animatsiyasi 1960-yillarda yaratilgan — oddiy chiziqlar edi.",
  "Pixar «Toy Story» (1995) — to'liq kompyuterda yasalgan birinchi to'liq metrajli film.",
  "Bitta animatsion film kadri renderiga soatlab vaqt ketishi mumkin — filmga yillar!",
  "Yashil ekran (xromakey) — yashil rang teridan eng uzoq rang bo'lgani uchun tanlangan.",
  "Kinoteatr proyektori sekundiga 24 kadr ko'rsatadi — miya buni harakat deb qabul qiladi.",
  "Birinchi GIF 1987-yilda yaratilgan — hali ham o'lmayapti!",
  "Adobe Photoshop dastlab aka-ukalar tomonidan uy sharoitida yozilgan (1987).",
  "3D kino ikki kameraning bir ozgina farqli tasviri — ko'zlarimiz kabi.",
  "Kompyuter shriftlari ham dastur — har harf matematik egri chiziqlar.",
  "Eng mashhur shriftlardan Times New Roman 1931-yilda gazeta uchun yaratilgan.",
  "Klaviatura «tugmalari ovozi»ni ataylab qo'shadigan ilovalar bor — kayfiyat uchun!",
  "Birinchi raqamli musiqa pleyeri MP3 uchun sudlar bo'lgan — endi hamma narsa streaming.",
  "Auto-Tune ovoz tuzatgichi aslida neft qidiruv texnologiyasidan chiqqan.",
  "Dolby ovoz tizimi kinoteatrda 60 dan ortiq karnaydan keladi.",
  "Siri'ning asl ovozi yozib olingan aktrisa buni yillar keyin bilgan.",
  "Google Translate avval so'zma-so'z o'girardi, endi butun gap ma'nosini AI biladi.",
  "Elektron lug'atlar bir soniyada million so'zni qidiradi — qog'ozda bir daqiqa ketardi.",
  "Braille displeylari ko'zi ojizlarga saytlarni «barmoq bilan o'qish» imkonini beradi.",
  "Subtitrlarni endi AI real vaqtda yozadi — jonli efirda ham.",
  "Xarita ilovalari tirbandlikni telefonlar harakatidan biladi — siz ham «sensor»siz!",
  "Uber-navigatsiya yo'lni har soniyada qayta hisoblaydi.",
  "Parkovka sensori ultratovush chiqaradi — ko'rshapalak kabi.",
  "Avtomobil ABS tormozi sekundiga o'nlab marta tormozni bosib-qo'yib turadi.",
  "Poyezdlar ham «autopilot»da yura oladi — ba'zi metrolar haydovchisiz.",
  "Samolyot avtopiloti parvozning ~90% qismini boshqaradi, qo'nishni ko'pincha uchuvchi qiladi.",
  "Aeroportdagi bagaj tizimi — millionlab jomadonni saralaydigan ulkan robot-konveyer.",
  "Chipta QR-kodi ichida ism, reys va o'rindiq shifrlangan.",
  "Yo'l svetoforlari aqlli shaharlarda trafikka qarab o'zi moslashadi.",
  "Ko'priklarning sensorlari tebranishni o'lchab, ta'mir vaqtini aytadi.",
  "Zilzilani sensorlar to'lqin yetib kelishidan bir necha soniya OLDIN sezishi mumkin — ogohlantirish yuboriladi.",
  "Ob-havo radarlari yomg'ir tomchilaridan qaytgan signalni o'qiydi.",
  "Sun'iy yo'ldoshlar okeandagi kemalarni ham kuzatadi — har kema «ko'rinadi».",
  "Chuqur dengiz tubining faqat ~25% batafsil xaritalangan — Mars yaxshiroq o'rganilgan!",
  "Suv osti kabelini akulalar tishlagan hollari bo'lgan — endi maxsus qoplama bor.",
  "Antarktidada ham internet bor — lekin sekin va sun'iy yo'ldosh orqali.",
  "Everest cho'qqisida 4G ishlaydi — bazaviy stansiya 5300 m balandlikda.",
  "Eng chuqur joyga (Mariana botig'i) odam tushgan — 10 916 metr.",
  "Muzliklardagi burg'ulangan namunalar 800 ming yillik havoni saqlaydi.",
  "DNK'da ma'lumot saqlash sinovdan o'tgan — 1 grammda millionlab GB!",
  "Inson genomi birinchi marta 2003-yilda to'liq o'qilgan — 13 yil ketgan; endi bir kunda o'qiladi.",
  "Sun'iy yurak klapanlari 3D printerda bosiladi.",
  "Protez qo'llar endi miyadan signal oladi — o'ylash bilan harakatlanadi.",
  "Eshitish apparatlari endi Bluetooth naushnik vazifasini ham bajaradi.",
  "Operatsiya xonasidagi robotning qo'li inson qo'lidan titramaydi.",
  "Rentgen nurlari tasodifan kashf qilingan (1895) — birinchi surat: xotinining qo'li.",
  "Termometr, tonometr, glyukometr — hammasi endi smartfonga ulanadi.",
  "Fitnes-bilaguzuklar uyquni harakat va yurak urishidan «o'qiydi».",
  "Dunyodagi eng katta teleskoplar cho'llarga quriladi — havo toza va quruq.",
  "Radio teleskoplar «eshitadi»: yulduzlar radioto'lqinlarini ham qabul qiladi.",
  "O'zbekistondagi Maydanak observatoriyasi dunyodagi eng yaxshi astro-nuqtalardan biri.",
  "Kosmik apparatlar Yerga suratni radioto'lqin bilan yuboradi — Marsdan ~20 daqiqa yo'l.",
  "Birinchi kosmik selfi 1966-yilda olingan — Buzz Aldrin ochiq kosmosda.",
  "Xalqaro kosmik stansiyani oddiy ko'z bilan ko'rsa bo'ladi — eng yorqin «yulduz»lardan.",
  "Astronavtlar qaytgach yana yurishni o'rganadi — muskullar vaznsizlikda «dangasalashadi».",
];

// Tasodifiy fakt (oldingisidan farqli bo'lishiga harakat qiladi)
export function randomFact(prev?: string): string {
  if (FACTS.length < 2) return FACTS[0] ?? "";
  let f = FACTS[Math.floor(Math.random() * FACTS.length)];
  while (f === prev) f = FACTS[Math.floor(Math.random() * FACTS.length)];
  return f;
}
